from __future__ import annotations

from typing import Iterator

from luxar.core.config_manager import AgentConfig


def run_task_stream_entrypoint(
    *,
    config: AgentConfig,
    project_root: str,
    workspace_root: str,
    driver_library_root: str,
    task: str,
    project_name: str = "",
    docs: list[str] | None = None,
    dry_run: bool = False,
    plan_only: bool = False,
    no_build: bool = False,
    no_flash: bool = False,
    no_monitor: bool = False,
    prepare_legacy_task_invocation,
    build_workflow_started_event,
    dispatch_stream_task_core,
    stream_legacy_task_result,
    project_manager_cls,
    runtime_adapters_module,
    stream_event,
    build_task_result,
    auto_fix_rule_ids,
    should_auto_apply_review_fixes,
    auto_fix_review_files,
    build_review_message,
    infer_driver_request,
    should_run_build_only,
    build_build_message,
    build_explain_message,
    prepare_task_execution,
    workflow_name_from_execution_plan,
) -> Iterator[dict]:
    docs, execution_plan, engineering, workflow_name = prepare_legacy_task_invocation(
        task=task,
        project_name=project_name,
        docs=docs,
        dry_run=dry_run,
        plan_only=plan_only,
        driver_library_root=driver_library_root,
        prepare_task_execution=prepare_task_execution,
        workflow_name_from_execution_plan_fn=workflow_name_from_execution_plan,
    )
    yield build_workflow_started_event(
        task=task,
        workflow_name=workflow_name,
        execution_plan=execution_plan,
        engineering=engineering,
    )

    stream = dispatch_stream_task_core(
        config=config,
        project_root=project_root,
        workspace_root=workspace_root,
        driver_library_root=driver_library_root,
        task=task,
        project_name=project_name,
        docs=docs,
        execution_plan=execution_plan,
        engineering=engineering,
        dry_run=dry_run,
        plan_only=plan_only,
        no_build=no_build,
        no_flash=no_flash,
        no_monitor=no_monitor,
        stream_mode=True,
        project_manager_cls=project_manager_cls,
        runtime_adapters_module=runtime_adapters_module,
        stream_event=stream_event,
        build_task_result=build_task_result,
        auto_fix_rule_ids=auto_fix_rule_ids,
        should_auto_apply_review_fixes=should_auto_apply_review_fixes,
        auto_fix_review_files=auto_fix_review_files,
        build_review_message=build_review_message,
        infer_driver_request=infer_driver_request,
        should_run_build_only=should_run_build_only,
        build_build_message=build_build_message,
        build_explain_message=build_explain_message,
        workflow_name_from_execution_plan=workflow_name_from_execution_plan,
    )
    yield from stream_legacy_task_result(stream=stream, workflow_name=workflow_name)


def run_task_entrypoint(
    *,
    config: AgentConfig,
    project_root: str,
    workspace_root: str,
    driver_library_root: str,
    task: str,
    project_name: str = "",
    docs: list[str] | None = None,
    dry_run: bool = False,
    plan_only: bool = False,
    no_build: bool = False,
    no_flash: bool = False,
    no_monitor: bool = False,
    prepare_legacy_task_invocation,
    consume_stream_result,
    dispatch_stream_task_core,
    project_manager_cls,
    runtime_adapters_module,
    stream_event,
    build_task_result,
    auto_fix_rule_ids,
    should_auto_apply_review_fixes,
    auto_fix_review_files,
    build_review_message,
    infer_driver_request,
    should_run_build_only,
    build_build_message,
    build_explain_message,
    prepare_task_execution,
    workflow_name_from_execution_plan,
) -> dict:
    docs, execution_plan, engineering, _workflow_name = prepare_legacy_task_invocation(
        task=task,
        project_name=project_name,
        docs=docs,
        dry_run=dry_run,
        plan_only=plan_only,
        driver_library_root=driver_library_root,
        prepare_task_execution=prepare_task_execution,
        workflow_name_from_execution_plan_fn=workflow_name_from_execution_plan,
    )

    return consume_stream_result(dispatch_stream_task_core(
        config=config,
        project_root=project_root,
        workspace_root=workspace_root,
        driver_library_root=driver_library_root,
        task=task,
        project_name=project_name,
        docs=docs,
        execution_plan=execution_plan,
        engineering=engineering,
        dry_run=dry_run,
        plan_only=plan_only,
        no_build=no_build,
        no_flash=no_flash,
        no_monitor=no_monitor,
        stream_mode=False,
        project_manager_cls=project_manager_cls,
        runtime_adapters_module=runtime_adapters_module,
        stream_event=stream_event,
        build_task_result=build_task_result,
        auto_fix_rule_ids=auto_fix_rule_ids,
        should_auto_apply_review_fixes=should_auto_apply_review_fixes,
        auto_fix_review_files=auto_fix_review_files,
        build_review_message=build_review_message,
        infer_driver_request=infer_driver_request,
        should_run_build_only=should_run_build_only,
        build_build_message=build_build_message,
        build_explain_message=build_explain_message,
        workflow_name_from_execution_plan=workflow_name_from_execution_plan,
    ))
