from __future__ import annotations

from datetime import datetime
from pathlib import Path

import git
from git.exc import BadName


class GitManager:
    def __init__(self, repo_path: str):
        self.repo_path = Path(repo_path)
        self.repo = git.Repo.init(self.repo_path)

    def create_branch(self, branch_name: str) -> None:
        if branch_name in {head.name for head in self.repo.heads}:
            self.repo.heads[branch_name].checkout()
            return
        head = self.repo.create_head(branch_name)
        head.checkout()

    def commit_agent_action(
        self, action: str, files: list[str], base_commit: str | None = None
    ) -> str:
        self.repo.index.add(files)
        message = (
            f"[Agent] {action} | {datetime.now().isoformat()}\n\n"
            "Auto-generated by Luxar\n"
            f"Files: {', '.join(files)}\n"
            "Agent-Commit: true\n"
        )
        if base_commit:
            message += f"Agent-Base-Commit: {base_commit}\n"
        commit = self.repo.index.commit(message)
        return commit.hexsha

    def find_last_human_commit(self) -> str | None:
        try:
            for commit in self.repo.iter_commits():
                if "Agent-Commit: true" not in commit.message:
                    return commit.hexsha
        except (ValueError, BadName):
            return None
        return None

    def rollback_last_agent_commit(self) -> str:
        if self.repo.is_dirty(untracked_files=True):
            raise RuntimeError("Working tree is dirty; refusing to auto-rollback.")
        head = self.repo.head.commit
        if "Agent-Commit: true" not in head.message:
            raise RuntimeError("HEAD is not an agent commit.")
        self.repo.git.revert(head.hexsha, no_edit=True)
        return head.hexsha

    def get_diff_since_last_human_commit(self) -> str:
        base = self.find_last_human_commit()
        if base is None:
            try:
                return self.repo.git.diff()
            except (ValueError, BadName):
                return ""
        return self.repo.git.diff(base, "HEAD")

    def changed_files(self) -> dict:
        """Return modified and untracked files. Keys: 'modified', 'untracked'."""
        modified = [item.a_path for item in self.repo.index.diff(None)]
        untracked = self.repo.untracked_files
        return {"modified": modified, "untracked": untracked}


