"""可演进的项目级 Agent 领域模型。

该包与 legacy 的 :mod:`luxar.domain.requirements` 和
:mod:`luxar.domain.plans` 并存，避免新模型尚未完成时破坏已有 checkpoint。
"""

from luxar.domain.agent.acceptance import AcceptanceCriterion, AcceptanceVerifier
from luxar.domain.agent.capabilities import (
    ProjectCapability,
    ProjectCapabilityExtractor,
    PreserveViolationError,
    find_preserve_violations,
)
from luxar.domain.agent.build_recovery import (
    BuildFailureAdvisor,
    BuildRecoveryDecision,
)
from luxar.domain.agent.sdk_probe import (
    SdkIncludeResolution,
    SdkMigrationSnippet,
    changed_api_names,
    missing_include_names,
)
from luxar.domain.agent.code_changes import (
    ChangeBundle,
    ChangeBundleError,
    ChangeBundleValidation,
    FileChange,
    apply_bundle_to_snapshot,
    snapshot_fingerprint,
    validate_change_bundle,
)
from luxar.domain.agent.changes import (
    CapabilityChange,
    ChangeSet,
    InteractionIntent,
    ObjectiveInterpretation,
    ObjectiveInterpreter,
)
from luxar.domain.agent.failures import (
    AgentFailureRecord,
    decide_failure_status,
    failure_signature,
)
from luxar.domain.agent.hardware import (
    BoardProfile,
    ChipProfile,
    DeviceSpec,
    ESP32_PROFILE,
    HardwareAssignment,
    HardwareRuleEngine,
    HardwareValidationIssue,
    HardwareValidationReport,
    ModuleProfile,
    ProtocolPackage,
)
from luxar.domain.agent.objectives import ProjectObjective
from luxar.domain.agent.runtime_verification import (
    EvidenceCheckResult,
    ProtocolProbeEvidence,
    ProtocolProbeSpec,
    ProtocolProbeVerifier,
    RuntimeScenarioEvidence,
    RuntimeScenarioSpec,
    RuntimeScenarioVerifier,
)
from luxar.domain.agent.project_inspector import ProjectModelExtractor
from luxar.domain.agent.project_model import (
    ComponentDependency,
    ComponentGraph,
    ComponentNode,
    DataFlow,
    DataFlowEdge,
    DataFlowNode,
    ProjectConfiguration,
    ProjectFact,
    ProjectModel,
    ResourceAllocation,
    ResourceConflict,
    ResourceGraph,
)
from luxar.domain.agent.tasks import (
    AgentTask,
    AgentTaskGraph,
    TaskGraphDiff,
    TaskGraphRevision,
    build_task_graph,
    diff_task_graph,
    revise_task_graph,
)
from luxar.domain.agent.verification import (
    AssertionResult,
    ComponentTestEvidence,
    ComponentTestSpec,
    DeviceLogAssertion,
    DeviceLogVerifier,
    FirmwareMetricAssertion,
    FirmwareResourceEvidence,
    FirmwareResourceVerifier,
    SourceAssertion,
    SourceAssertionVerifier,
    VerificationPlan,
    VerificationRun,
)

__all__ = [
    "AcceptanceCriterion",
    "AcceptanceVerifier",
    "AssertionResult",
    "ComponentTestEvidence",
    "ComponentTestSpec",
    "AgentFailureRecord",
    "BoardProfile",
    "BuildFailureAdvisor",
    "BuildRecoveryDecision",
    "ChipProfile",
    "DeviceSpec",
    "DeviceLogAssertion",
    "DeviceLogVerifier",
    "FirmwareMetricAssertion",
    "FirmwareResourceEvidence",
    "FirmwareResourceVerifier",
    "ESP32_PROFILE",
    "EvidenceCheckResult",
    "AgentTask",
    "AgentTaskGraph",
    "CapabilityChange",
    "ChangeBundle",
    "ChangeBundleError",
    "ChangeBundleValidation",
    "ChangeSet",
    "ComponentDependency",
    "ComponentGraph",
    "ComponentNode",
    "DataFlow",
    "DataFlowEdge",
    "DataFlowNode",
    "FileChange",
    "InteractionIntent",
    "HardwareAssignment",
    "HardwareRuleEngine",
    "HardwareValidationIssue",
    "HardwareValidationReport",
    "ObjectiveInterpretation",
    "ObjectiveInterpreter",
    "ProjectCapability",
    "ProjectCapabilityExtractor",
    "ProjectConfiguration",
    "ProjectFact",
    "ProjectModel",
    "ProjectModelExtractor",
    "ProjectObjective",
    "ModuleProfile",
    "ProtocolPackage",
    "ProtocolProbeEvidence",
    "ProtocolProbeSpec",
    "ProtocolProbeVerifier",
    "PreserveViolationError",
    "ResourceAllocation",
    "ResourceConflict",
    "ResourceGraph",
    "RuntimeScenarioEvidence",
    "RuntimeScenarioSpec",
    "RuntimeScenarioVerifier",
    "SourceAssertion",
    "SourceAssertionVerifier",
    "TaskGraphDiff",
    "TaskGraphRevision",
    "build_task_graph",
    "apply_bundle_to_snapshot",
    "diff_task_graph",
    "decide_failure_status",
    "failure_signature",
    "find_preserve_violations",
    "revise_task_graph",
    "snapshot_fingerprint",
    "validate_change_bundle",
    "VerificationPlan",
    "VerificationRun",
    "SdkIncludeResolution",
    "SdkMigrationSnippet",
    "changed_api_names",
    "missing_include_names",
]
