"""解析 LUXAR font.export 生成的字模 C 头文件，供设备侧自检重建帧使用。

字模头文件由 ``font.export`` 确定性生成，格式固定：``#define`` 尺寸宏、
主字节数组 ``const uint8_t NAME[]``、混合宽度时的 ``GLYPH_WIDTHS`` /
``GLYPH_OFFSETS``、含宽字符时的 ``CODEPOINTS``，以及每字形 ``crc32``
注释与 ``data_crc32`` / ``data_sha256`` 锚点。

解析器只信任 LUXAR 生成的头部（含 “Auto-generated by LUXAR font.extract”
标记），避免把任意 C 文件当字模解析。
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from luxar.adapters.font_bitmap import FontBitmapError

_GENERATED_MARK = "Auto-generated by LUXAR font.extract"
_DEFINE_RE = re.compile(r"#define\s+(\w+)_(WIDTH|HEIGHT|GLYPH_COUNT|BYTES_PER_GLYPH|TOTAL_BYTES)\s+(\d+)")
_U8_ARRAY_RE = re.compile(
    r"const\s+uint8_t\s+(\w+)\[\]\s*=\s*\{(.*?)\};", re.DOTALL
)
_U8_LIST_RE = re.compile(
    r"const\s+uint8_t\s+(\w+)_GLYPH_WIDTHS\[(\d+)\]\s*=\s*\{(.*?)\};", re.DOTALL
)
_U16_LIST_RE = re.compile(
    r"const\s+uint16_t\s+(\w+)_(GLYPH_OFFSETS|CODEPOINTS)\[(\d+)\]\s*=\s*\{(.*?)\};",
    re.DOTALL,
)
_HEX_BYTE_RE = re.compile(r"0[xX]([0-9A-Fa-f]{2})")
_HEX_CODEPOINT_RE = re.compile(r"0[xX]([0-9A-Fa-f]{4})")
_DATA_CRC_RE = re.compile(r"data_crc32=([0-9A-Fa-f]{8})")
_DATA_SHA_RE = re.compile(r"data_sha256=([0-9A-Fa-f]{64})")
_GLYPH_CRC_RE = re.compile(r"(?<!data_)crc32=([0-9A-Fa-f]{8})")
# 机器可读布局标记（format_c_header 输出）：layout_scan=column layout_bit_order=lsb layout_invert=0
_LAYOUT_MARK_RE = re.compile(
    r"layout_scan=(\w+)\s+layout_bit_order=(\w+)\s+layout_invert=([01])"
)


@dataclass(frozen=True)
class ParsedFontHeader:
    array_name: str
    width: int
    height: int
    glyph_count: int
    bytes_per_glyph: int
    total_bytes: int
    data: bytes
    glyph_widths: list[int]
    glyph_offsets: list[int]
    codepoints: list[int]
    data_crc32: str
    data_sha256: str
    glyph_crc32s: list[str]
    #: 字模打包时声明的布局（机器可读标记）；旧文件无标记时为 None
    layout_scan: str | None = None
    layout_bit_order: str | None = None
    layout_invert: bool | None = None

    def glyph_data(self, index: int) -> bytes:
        start = self.glyph_offsets[index]
        end = self.glyph_offsets[index + 1]
        return self.data[start:end]


def _hex_bytes_list(body: str) -> list[int]:
    return [int(item, 16) for item in _HEX_BYTE_RE.findall(body)]


def _decimal_list(body: str) -> list[int]:
    return [int(item) for item in re.findall(r"\d+", body)]


def parse_font_header(source: Path | str) -> ParsedFontHeader:
    """解析 LUXAR 生成的字模头文件；非 LUXAR 生成或格式不符时抛错。"""
    path = Path(source)
    if not path.is_file():
        raise FontBitmapError(
            "font_header_not_found",
            f"字模头文件不存在：{path}",
            details={"header_path": str(path)},
        )
    content = path.read_text(encoding="utf-8")
    if _GENERATED_MARK not in content:
        raise FontBitmapError(
            "font_header_not_luxar",
            "文件不是 LUXAR font.export 生成的字模头文件",
            details={"header_path": str(path)},
        )
    defines = {
        f"{match.group(1)}_{match.group(2)}": int(match.group(3))
        for match in _DEFINE_RE.finditer(content)
    }
    if len(defines) < 4:
        raise FontBitmapError(
            "font_header_missing_defines",
            "字模头文件缺少尺寸宏",
            details={"header_path": str(path)},
        )
    u8_matches = _U8_ARRAY_RE.findall(content)
    if not u8_matches:
        raise FontBitmapError(
            "font_header_missing_data",
            "字模头文件缺少主字节数组",
            details={"header_path": str(path)},
        )
    array_name = u8_matches[0][0]
    data = bytes(_hex_bytes_list(u8_matches[0][1]))
    glyph_widths = _decimal_list(
        next((m.group(3) for m in _U8_LIST_RE.finditer(content) if m.group(1) == array_name), "")
    )
    lists_16 = {
        m.group(2): (
            _decimal_list(m.group(4))
            if m.group(2) == "GLYPH_OFFSETS"
            else [int(item, 16) for item in _HEX_CODEPOINT_RE.findall(m.group(4))]
        )
        for m in _U16_LIST_RE.finditer(content)
        if m.group(1) == array_name
    }
    glyph_offsets = lists_16.get("GLYPH_OFFSETS", [])
    codepoints = lists_16.get("CODEPOINTS", [])
    if not codepoints:
        # 纯 ASCII 字库没有 CODEPOINTS 表：按 0x20 起连续码点推导
        codepoints = list(range(0x20, 0x20 + len(glyph_widths)))
    glyph_crc32s = [
        match.group(1)
        for match in _GLYPH_CRC_RE.finditer(content)
    ]
    data_crc = _DATA_CRC_RE.search(content)
    data_sha = _DATA_SHA_RE.search(content)
    width = defines.get(f"{array_name}_WIDTH", 0)
    height = defines.get(f"{array_name}_HEIGHT", 0)
    glyph_count = defines.get(f"{array_name}_GLYPH_COUNT", 0)
    bytes_per_glyph = defines.get(f"{array_name}_BYTES_PER_GLYPH", 0)
    total_bytes = defines.get(f"{array_name}_TOTAL_BYTES", 0)
    if width <= 0 or height <= 0 or glyph_count <= 0:
        raise FontBitmapError(
            "font_header_invalid_sizes",
            "字模头文件尺寸宏无效",
            details={"header_path": str(path)},
        )
    if glyph_widths and len(glyph_widths) != glyph_count:
        raise FontBitmapError(
            "font_header_width_mismatch",
            "GLYPH_WIDTHS 数量与 GLYPH_COUNT 不一致",
            details={
                "glyph_count": glyph_count,
                "width_count": len(glyph_widths),
            },
        )
    if glyph_offsets:
        if len(glyph_offsets) != glyph_count + 1:
            raise FontBitmapError(
                "font_header_offsets_mismatch",
                "GLYPH_OFFSETS 数量应为 GLYPH_COUNT + 1",
                details={
                    "glyph_count": glyph_count,
                    "offset_count": len(glyph_offsets),
                },
            )
        if glyph_offsets[-1] != len(data):
            raise FontBitmapError(
                "font_header_data_length_mismatch",
                "字形数据长度与 GLYPH_OFFSETS 末尾不一致",
                details={
                    "data_bytes": len(data),
                    "last_offset": glyph_offsets[-1],
                },
            )
    if not glyph_offsets:
        # 统一宽度字库：每字形 bytes_per_glyph 字节
        glyph_offsets = [
            index * bytes_per_glyph for index in range(glyph_count + 1)
        ]
    if not glyph_widths:
        glyph_widths = [width] * glyph_count
    if len(codepoints) != glyph_count:
        codepoints = list(range(0x20, 0x20 + glyph_count))
    layout_mark = _LAYOUT_MARK_RE.search(content)
    layout_scan: str | None = None
    layout_bit_order: str | None = None
    layout_invert: bool | None = None
    if layout_mark is not None:
        layout_scan = layout_mark.group(1)
        layout_bit_order = layout_mark.group(2)
        layout_invert = layout_mark.group(3) == "1"
    return ParsedFontHeader(
        array_name=array_name,
        width=width,
        height=height,
        glyph_count=glyph_count,
        bytes_per_glyph=bytes_per_glyph,
        total_bytes=total_bytes or len(data),
        data=data,
        glyph_widths=glyph_widths,
        glyph_offsets=glyph_offsets,
        codepoints=codepoints,
        data_crc32=data_crc.group(1) if data_crc else "",
        data_sha256=data_sha.group(1) if data_sha else "",
        glyph_crc32s=glyph_crc32s,
        layout_scan=layout_scan,
        layout_bit_order=layout_bit_order,
        layout_invert=layout_invert,
    )


__all__ = ["ParsedFontHeader", "parse_font_header"]
