"""显示自检：设备侧参考实现模板 + 上位机帧校验。

闭环验证思路（对应 README“显示屏字模取模工具”一节）：

1. ``font.export`` 生成的字模头文件自带每字形 crc32 与整表 data_crc32/
   data_sha256 锚点；
2. 设备侧把同一个字模文件画到显存后，用本模块提供的 ``display_selfcheck``
   参考实现（零依赖 zlib CRC32）对整帧字节流计算 CRC，经 UART 打印
   ``FONT_CHECK <name> <crc32>``；
3. 上位机用 ``verify_display_selfcheck`` 解析工程内字模头文件、按同一坐标
   重建预期帧，与设备回传的 CRC 对比——一致即“驱动把正确的字模字节写到了
   正确的显存位置”，与模型自报无关。
"""

from __future__ import annotations

import hashlib
import zlib
from dataclasses import dataclass
from pathlib import Path

from luxar.adapters.font_bitmap import (
    FontBitmapError,
    FontLayout,
    frame_crc32,
    frame_sha256,
    render_frame_bytes,
)
from luxar.adapters.font_header import ParsedFontHeader, parse_font_header
from luxar.specs import find_chip_skill

# --------------------------------------------------------------------------
# 设备侧参考实现（C，零依赖）
# --------------------------------------------------------------------------

_CRC32_TABLE_ITEMS = []
for _value in range(256):
    _crc = _value
    for _ in range(8):
        _crc = (0xEDB88320 ^ (_crc >> 1)) if (_crc & 1) else (_crc >> 1)
    _CRC32_TABLE_ITEMS.append(f"0x{_crc:08X}U")

_CRC32_TABLE_TEXT = ",\n    ".join(
    ", ".join(_CRC32_TABLE_ITEMS[index : index + 6])
    for index in range(0, 256, 6)
)

DISPLAY_SELFCHECK_HEADER_TEMPLATE = """\
/* Auto-generated by LUXAR display.selfcheck_template - do not hand-edit. */
#ifndef DISPLAY_SELFCHECK_H
#define DISPLAY_SELFCHECK_H

#include <stddef.h>
#include <stdint.h>

/* 与上位机 display.verify 完全一致的 zlib CRC32（多项式 0xEDB88320）。 */
uint32_t display_selfcheck_crc32(const uint8_t *data, size_t len);

/* 计算整帧（screen_width * screen_height / 8 字节，页寻址布局）CRC32，
 * 并通过 UART 打印 FONT_CHECK <name> <crc32hex>，供上位机对比。 */
void display_selfcheck_report(
    const char *name,
    const uint8_t *framebuffer,
    size_t frame_bytes);

#endif /* DISPLAY_SELFCHECK_H */
"""

DISPLAY_SELFCHECK_SOURCE_TEMPLATE = """\
/* Auto-generated by LUXAR display.selfcheck_template - do not hand-edit. */
#include "display_selfcheck.h"
#include <stdio.h>

/* zlib 标准 CRC32 查找表（多项式 0xEDB88320）。 */
static const uint32_t s_crc32_table[256] = {
    __CRC32_TABLE__
};

uint32_t display_selfcheck_crc32(const uint8_t *data, size_t len) {
    uint32_t crc = 0xFFFFFFFFU;
    for (size_t i = 0; i < len; i++) {
        crc = s_crc32_table[(crc ^ data[i]) & 0xFFU] ^ (crc >> 8);
    }
    return crc ^ 0xFFFFFFFFU;
}

void display_selfcheck_report(
    const char *name,
    const uint8_t *framebuffer,
    size_t frame_bytes) {
    uint32_t crc = display_selfcheck_crc32(framebuffer, frame_bytes);
    printf("FONT_CHECK %s %08X\\n", name, (unsigned)crc);
}
""".replace("__CRC32_TABLE__", _CRC32_TABLE_TEXT)

DISPLAY_SELFCHECK_TEMPLATES: dict[str, str] = {
    "display_selfcheck.h": DISPLAY_SELFCHECK_HEADER_TEMPLATE,
    "display_selfcheck.c": DISPLAY_SELFCHECK_SOURCE_TEMPLATE,
}

# --------------------------------------------------------------------------
# 上位机校验
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class DisplaySelfCheckResult:
    lines: list[tuple[str, int, int]]
    screen_width: int
    screen_height: int
    header_path: str
    array_name: str
    frame_bytes: int
    expected_crc32: str
    expected_sha256: str
    actual_crc32: str | None
    actual_sha256: str | None
    match: bool
    header_data_integrity: bool
    glyph_crc32s: dict[str, str]
    #: 控制器规格布局（controller 参数解析后）
    spec_layout: FontLayout | None = None
    #: 字模头文件声明的布局（无标记时为 None）
    header_layout: FontLayout | None = None
    #: 布局一致性：True=一致/无法检测，False=字模声明与控制器规格冲突（已报错前置）
    layout_consistent: bool = True
    #: 控制器规格 verified 状态（unverified 提示用）
    spec_verified: str | None = None


def _layout_mismatch_error(
    controller: str,
    header_layout: FontLayout | None,
    spec_layout: FontLayout,
) -> FontBitmapError:
    header_desc = header_layout.human if header_layout is not None else "（无标记，旧文件）"
    return FontBitmapError(
        "display_layout_mismatch",
        "字模打包布局与控制器规格冲突：字模声明 "
        + header_desc
        + "，但控制器 "
        + controller
        + " 的规格（src/luxar/specs/chips/）是 "
        + spec_layout.human
        + "。按控制器规格重新取模（font.export 传 controller=该芯片，或显式 "
        "scan/bit_order/invert），否则设备显示必然乱码（CRC 自检无法发现位序约定错误）。",
        details={
            "controller": controller,
            "header_layout": (
                {
                    "scan": header_layout.scan,
                    "bit_order": header_layout.bit_order,
                    "invert": header_layout.invert,
                }
                if header_layout is not None
                else None
            ),
            "spec_layout": {
                "scan": spec_layout.scan,
                "bit_order": spec_layout.bit_order,
                "invert": spec_layout.invert,
            },
        },
    )


def verify_display_selfcheck(
    *,
    header_path: Path,
    lines: list[tuple[str, int, int]],
    screen_width: int = 128,
    screen_height: int = 64,
    actual_crc32: str | None = None,
    actual_sha256: str | None = None,
    controller: str | None = None,
) -> DisplaySelfCheckResult:
    """解析字模头文件、按多行布局重建预期帧，与设备回传的 CRC/SHA 对比。

    ``lines`` 为 [(text, x, y), ...]；每行按页寻址绘制进同一帧（逐行
    OR 合并，等价于设备侧在同一显存连续绘制多行）。

    传入 ``controller`` 时，用芯片规格的已知硬件约定做**约定级校验**：
    字模头文件声明的打包布局（layout_scan/bit_order/invert 标记）若与
    控制器规格冲突，直接抛 FontBitmapError（display_layout_mismatch）——
    把位序/行序约定错误在自检阶段暴露，而不是等真机乱码才发现
    （CRC 自检证明不了约定与硬件一致）。spec verified != true 时在结果中
    附 spec_verified 供上层提示"位序未经真机验证"。
    """
    parsed: ParsedFontHeader = parse_font_header(header_path)
    spec_layout: FontLayout | None = None
    spec_verified: str | None = None
    if controller is not None:
        skill = find_chip_skill(controller)
        if skill is not None and skill.display is not None:
            spec_layout = FontLayout(
                scan=skill.display.layout.scan,
                bit_order=skill.display.layout.bit_order,
                invert=skill.display.layout.invert,
            )
            spec_verified = skill.verified
    header_layout: FontLayout | None = None
    if (
        parsed.layout_scan is not None
        and parsed.layout_bit_order is not None
        and parsed.layout_invert is not None
    ):
        header_layout = FontLayout(
            scan=parsed.layout_scan,
            bit_order=parsed.layout_bit_order,
            invert=parsed.layout_invert,
        )
    layout_consistent = True
    if (
        spec_layout is not None
        and header_layout is not None
        and header_layout != spec_layout
    ):
        raise _layout_mismatch_error(controller or "", header_layout, spec_layout)
    pages_total = screen_height // 8
    frame = bytearray(pages_total * screen_width)
    for text, x, y in lines:
        row = render_frame_bytes(
            data=parsed.data,
            glyph_offsets=parsed.glyph_offsets,
            glyph_widths=parsed.glyph_widths,
            codepoints=parsed.codepoints,
            glyph_height=parsed.height,
            text=text,
            x=x,
            y=y,
            screen_width=screen_width,
            screen_height=screen_height,
        )
        for index, value in enumerate(row):
            frame[index] |= value
    frame = bytes(frame)
    expected_crc32 = frame_crc32(frame)
    expected_sha256 = frame_sha256(frame)
    glyph_map: dict[str, str] = {}
    for index, codepoint in enumerate(parsed.codepoints):
        if index < len(parsed.glyph_crc32s):
            glyph_map[chr(codepoint)] = parsed.glyph_crc32s[index]
    integrity = True
    if parsed.data_crc32:
        actual_data_crc = f"{zlib.crc32(parsed.data) & 0xFFFFFFFF:08X}"
        integrity = integrity and actual_data_crc == parsed.data_crc32
    if parsed.data_sha256:
        actual_data_sha = hashlib.sha256(parsed.data).hexdigest()
        integrity = integrity and actual_data_sha == parsed.data_sha256
    crc_match = actual_crc32 is not None and actual_crc32.upper() == expected_crc32
    sha_match = (
        actual_sha256 is None
        or actual_sha256.lower() == expected_sha256
    )
    return DisplaySelfCheckResult(
        lines=lines,
        screen_width=screen_width,
        screen_height=screen_height,
        header_path=str(header_path),
        array_name=parsed.array_name,
        frame_bytes=len(frame),
        expected_crc32=expected_crc32,
        expected_sha256=expected_sha256,
        actual_crc32=(actual_crc32.upper() if actual_crc32 else None),
        actual_sha256=(actual_sha256.lower() if actual_sha256 else None),
        match=crc_match and sha_match,
        header_data_integrity=integrity,
        glyph_crc32s=glyph_map,
        spec_layout=spec_layout,
        header_layout=header_layout,
        layout_consistent=layout_consistent,
        spec_verified=spec_verified,
    )


def render_expected_frame(
    *,
    header_path: Path,
    lines: list[tuple[str, int, int]],
    screen_width: int = 128,
    screen_height: int = 64,
) -> bytes:
    """只重建预期帧字节流（供调试/预览，不校验）。"""
    parsed: ParsedFontHeader = parse_font_header(header_path)
    pages_total = screen_height // 8
    frame = bytearray(pages_total * screen_width)
    for text, x, y in lines:
        row = render_frame_bytes(
            data=parsed.data,
            glyph_offsets=parsed.glyph_offsets,
            glyph_widths=parsed.glyph_widths,
            codepoints=parsed.codepoints,
            glyph_height=parsed.height,
            text=text,
            x=x,
            y=y,
            screen_width=screen_width,
            screen_height=screen_height,
        )
        for index, value in enumerate(row):
            frame[index] |= value
    return bytes(frame)


__all__ = [
    "DISPLAY_SELFCHECK_HEADER_TEMPLATE",
    "DISPLAY_SELFCHECK_SOURCE_TEMPLATE",
    "DISPLAY_SELFCHECK_TEMPLATES",
    "DisplaySelfCheckResult",
    "render_expected_frame",
    "verify_display_selfcheck",
]
